== What is this app?

This is an example of a Spring Cloud Stream processor using Kafka Streams support

The application uses one inputs - one KStream for User changes
and groups by the User key into KTable 'allusers' then streams out the changes to 'usertable'

==== View the users
You can query the KTable using Rest endpoint http://localhost:8080/user/{id}
You can also see the output of the KTable on a scheduled print to the console.

=== Configs (application.yml)
spring.application.name: stream-global-table
spring.cloud.stream.bindings.process-in-0:
  destination: user
spring.cloud.stream.bindings.process-out-0:
  destination: usertable

=== Running the app:
    start Kafka and start producing the user to 'user' topic
   
   *** Create some users in the input table 'user' using the confluent cli or kafka cli
    
    'bin/confluent local produce user'  // this command is for Confluent platform, use Kafka commands for Kafka only installation

    {"id": "1", "name": "paul", "age": 44}
    {"id": "2", "name": "john", "age": 43}
    {"id": "3", "name": "virat", "age": 45}
    {"id": "4", "name": "asha", "age": 100}
    {"id": "5", "name": "paul", "age": 990}

    *** Update users

    {"id": "2", "name": "john", "age": 99}
    {"id": "3", "name": "virat", "age": 0}

==== View the users
    http://localhost:8080/user/{id}

    Also the app will print the usertable in the console



